steps:
  - name: gcr.io/cloud-builders/docker
    args:
      - build
      - -t
      - $_AR_HOSTNAME/$PROJECT_ID/cloud-run-source-deploy/$REPO_NAME/$_SERVICE_NAME:$COMMIT_SHA
      - -f
      - Dockerfile
      - .

  - name: gcr.io/cloud-builders/docker
    args:
      - push
      - $_AR_HOSTNAME/$PROJECT_ID/cloud-run-source-deploy/$REPO_NAME/$_SERVICE_NAME:$COMMIT_SHA

  - name: gcr.io/google.com/cloudsdktool/cloud-sdk
    entrypoint: gcloud
    args:
      - run
      - deploy
      - $_SERVICE_NAME
      - --image=$_AR_HOSTNAME/$PROJECT_ID/cloud-run-source-deploy/$REPO_NAME/$_SERVICE_NAME:$COMMIT_SHA
      - --region=$_DEPLOY_REGION
      - --platform=managed
      - --allow-unauthenticated
      - --cpu=1
      - --memory=512Mi
      - --min-instances=0
      - --max-instances=10
      - --concurrency=80
      - --timeout=300
      - --set-env-vars=^---^APP_ENV=production---APP_DEBUG=false---APP_URL=https://anteconnect.duckdns.org---DB_CONNECTION=pgsql---DB_HOST=/cloudsql/$_CLOUD_SQL_INSTANCE---DB_PORT=5432---DB_DATABASE=anteconect---DB_USERNAME=postgres---SANCTUM_STATEFUL_DOMAINS=anteconnect.duckdns.org,consumer-ten.vercel.app,admin-tau-two-97.vercel.app,localhost---SESSION_DRIVER=file---CACHE_DRIVER=file---FILESYSTEM_DISK=gcs---FILESYSTEM_PUBLIC_DRIVER=gcs---GOOGLE_CLOUD_STORAGE_BUCKET=$_STORAGE_BUCKET---QUEUE_CONNECTION=database---LOG_CHANNEL=stack---LOG_LEVEL=error
      - --set-secrets=APP_KEY=APP_KEY:latest,DB_PASSWORD=DB_PASSWORD:latest,FIREBASE_CREDENTIALS=FIREBASE_CREDENTIALS:latest,GOOGLE_CLOUD_PROJECT_ID=GOOGLE_CLOUD_PROJECT_ID:latest
      - --service-account=$_SERVICE_ACCOUNT
      - --set-cloud-sql-instances=$_CLOUD_SQL_INSTANCE
      - --execution-environment=gen2

  - name: gcr.io/google.com/cloudsdktool/cloud-sdk
    entrypoint: sh
    args:
      - -c
      - |
        echo "Updating DuckDNS..."
        RUN_URL=$$(gcloud run services describe $_SERVICE_NAME --region=$_DEPLOY_REGION --format='value(status.url)')
        HOST=$$(echo "$$RUN_URL" | sed 's|https://||' | sed 's|/||')
        IP=$$(dig +short "$$HOST" | tail -n1)
        echo "$$HOST -> $$IP"
        curl -s "https://duckdns.org/update?domains=anteconnect&token=$_DUCKDNS_TOKEN&ip=$$IP"
        echo ""

substitutions:
  _AR_HOSTNAME: asia-southeast1-docker.pkg.dev
  _SERVICE_NAME: anteco-connect-api
  _DEPLOY_REGION: asia-southeast1
  _CLOUD_SQL_INSTANCE: antecoconnect:asia-southeast1:anteconect-db
  _STORAGE_BUCKET: anteconect-uploads
  _SERVICE_ACCOUNT: anteco-connect-sa@antecoconnect.iam.gserviceaccount.com
  _DUCKDNS_TOKEN: 3abe99b5-b9ac-4293-9eff-c44e649bc62e

options:
  logging: CLOUD_LOGGING_ONLY
  machineType: E2_HIGHCPU_8

timeout: 1200s
